# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=100)),
                ('client_last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_first_name', models.CharField(max_length=100)),
                ('consultant_last_name', models.CharField(max_length=100)),
                ('consultant_specialty', models.CharField(choices=[('1', 'specialty1'), ('2', 'specialty2'), ('3', 'specialty3')], max_length=50)),
                ('consultant_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(choices=[('1', 'package1'), ('2', 'package2'), ('3', 'package3')], max_length=20)),
                ('package_start_date', models.DateField()),
                ('package_end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='client_consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddPerson.Consultant'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_packages',
            field=models.ManyToManyField(to='AddPerson.Package'),
        ),
    ]
