# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddPerson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_round', models.IntegerField()),
                ('application_school', models.CharField(choices=[('HBS', 'Harvard Business School'), ('MIT', 'Massachusetts Institute of Techonology')], max_length=10)),
                ('application_success', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(choices=[('1', 'package1'), ('2', 'package2'), ('3', 'package3')], max_length=1),
        ),
        migrations.AddField(
            model_name='client',
            name='client_application',
            field=models.ManyToManyField(to='AddPerson.Application'),
        ),
    ]
