# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 22:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AddPerson', '0002_auto_20170113_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_application',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_packages',
        ),
        migrations.AddField(
            model_name='application',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AddPerson.Client'),
        ),
        migrations.AddField(
            model_name='package',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AddPerson.Client'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_round',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_school',
            field=models.CharField(choices=[('N', 'None'), ('HBS', 'Harvard Business School'), ('MIT', 'Massachusetts Institute of Techonology')], max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AddPerson.Consultant'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='consultant_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='consultant_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='consultant_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='consultant_specialty',
            field=models.CharField(choices=[('N', 'None'), ('1', 'specialty1'), ('2', 'specialty2'), ('3', 'specialty3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_end_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(choices=[('N', 'None'), ('1', 'package1'), ('2', 'package2'), ('3', 'package3')], max_length=1),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_start_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
