# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 22:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddPerson', '0003_auto_20170114_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_round',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_school',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('HBS', 'Harvard Business School'), ('MIT', 'Massachusetts Institute of Techonology')], default='N', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='consultant_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='consultant_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='consultant_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='consultant_specialty',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('1', 'specialty1'), ('2', 'specialty2'), ('3', 'specialty3')], default='N', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_end_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('1', 'package1'), ('2', 'package2'), ('3', 'package3')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_start_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
