# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 04:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AddPerson', '0004_auto_20170115_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddmissionsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, choices=[('N', 'None'), ('1', 'package1'), ('2', 'package2'), ('3', 'package3')], default='N', max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('end_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Client services', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddPerson.AddmissionsEntry')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField(blank=True, default=0, null=True)),
                ('provider_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_specialty', models.CharField(blank=True, choices=[('N', 'None'), ('1', 'specialty1'), ('2', 'specialty2'), ('3', 'specialty3')], default='N', max_length=50, null=True)),
                ('provider_address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, choices=[('N', 'None'), ('HBS', 'Harvard Business School'), ('MIT', 'Massachusetts Institute of Techonology')], default='N', max_length=100, null=True)),
                ('owning_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddPerson.List')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, choices=[('N', 'None'), ('1', 'package1'), ('2', 'package2'), ('3', 'package3')], default='N', max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('end_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddPerson.Dictionary')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddPerson.Provider')),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='client',
        ),
        migrations.RemoveField(
            model_name='package',
            name='client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_consultant',
        ),
        migrations.AddField(
            model_name='consultant',
            name='payment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddPerson.Client'),
        ),
        migrations.AddField(
            model_name='addmissionsentry',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddPerson.Consultant'),
        ),
        migrations.AddField(
            model_name='addmissionsentry',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddPerson.Dictionary'),
        ),
    ]
