# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 23:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AddPerson', '0005_auto_20170116_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddmissionsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddPerson.Client')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddPerson.Client')),
            ],
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='client',
        ),
        migrations.RemoveField(
            model_name='list',
            name='entry',
        ),
        migrations.AlterField(
            model_name='addmissionsentry',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddPerson.AddmissionsList'),
        ),
        migrations.AlterField(
            model_name='addmissionsentry',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='addmissionsentry',
            name='service',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('1', 'package1'), ('2', 'package2'), ('3', 'package3')], db_index=True, default='N', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addmissionsentry',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='schoolentry',
            name='owning_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddPerson.SchoolList'),
        ),
        migrations.AlterField(
            model_name='schoolentry',
            name='school',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('HBS', 'Harvard Business School'), ('MIT', 'Massachusetts Institute of Techonology')], db_index=True, default='N', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddPerson.ServiceList'),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='service',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('1', 'package1'), ('2', 'package2'), ('3', 'package3')], db_index=True, default='N', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.datetime.now, null=True),
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.AddField(
            model_name='schoollist',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddPerson.AddmissionsEntry'),
        ),
    ]
