# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AddPerson', '0006_auto_20170117_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField(blank=True, default=0, null=True)),
                ('editor_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('editor_last_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='consultant',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AddPerson.Editor'),
        ),
    ]
