# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddPerson', '0007_auto_20170119_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='consultant',
            old_name='consultant_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='consultant',
            old_name='consultant_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='provider_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='provider_last_name',
            new_name='last_name',
        ),
    ]
