# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddPerson', '0008_auto_20170120_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='editor_first_name',
        ),
        migrations.AddField(
            model_name='editor',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
