# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 02:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AddPerson', '0009_auto_20170120_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, choices=[('N', 'None'), ('1', 'package1'), ('2', 'package2'), ('3', 'package3')], db_index=True, default='N', max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, db_index=True, default=datetime.datetime.now, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, default=datetime.datetime.now, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AddPerson.Client')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AddPerson.Provider')),
            ],
        ),
        migrations.RemoveField(
            model_name='schoolentry',
            name='owning_list',
        ),
        migrations.RemoveField(
            model_name='schoollist',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='serviceentry',
            name='container',
        ),
        migrations.RemoveField(
            model_name='serviceentry',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='servicelist',
            name='client',
        ),
        migrations.DeleteModel(
            name='SchoolEntry',
        ),
        migrations.DeleteModel(
            name='SchoolList',
        ),
        migrations.DeleteModel(
            name='ServiceEntry',
        ),
        migrations.DeleteModel(
            name='ServiceList',
        ),
        migrations.AddField(
            model_name='provider',
            name='clients',
            field=models.ManyToManyField(through='AddPerson.Service', to='AddPerson.Client'),
        ),
    ]
