# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 20:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AddPerson', '0010_auto_20170120_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddmissionsService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, choices=[('N', 'None'), ('1', 'package1'), ('2', 'package2'), ('3', 'package3')], db_index=True, default='N', max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, db_index=True, default=datetime.datetime.now, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, default=datetime.datetime.now, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AddPerson.Client')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AddPerson.Consultant')),
            ],
        ),
        migrations.RemoveField(
            model_name='addmissionsentry',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='addmissionsentry',
            name='container',
        ),
        migrations.RemoveField(
            model_name='addmissionslist',
            name='client',
        ),
        migrations.AlterField(
            model_name='provider',
            name='clients',
            field=models.ManyToManyField(blank=True, through='AddPerson.Service', to='AddPerson.Client'),
        ),
        migrations.DeleteModel(
            name='AddmissionsEntry',
        ),
        migrations.DeleteModel(
            name='AddmissionsList',
        ),
        migrations.AddField(
            model_name='consultant',
            name='clients',
            field=models.ManyToManyField(blank=True, through='AddPerson.AddmissionsService', to='AddPerson.Client'),
        ),
    ]
