# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddPerson', '0011_auto_20170121_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='addmissionsservice',
            name='schools',
            field=models.ManyToManyField(to='AddPerson.School'),
        ),
    ]
