# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddPerson', '0014_auto_20170207_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='application_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
