# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddPerson', '0016_remove_editor_editor_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
