# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddPerson', '0017_client_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmissionsservice',
            old_name='consultant',
            new_name='provider',
        ),
    ]
