# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddPerson', '0018_auto_20170225_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmissionsservice',
            name='entry_round',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='alternate_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='day_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='evening_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='hourly_capability',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultant',
            name='round_one_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='round_two_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='skype',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='text_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='hourly_capability',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='round_one_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='round_two_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='entry_round',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
